// campaign.js — FREEMON campaign data: 10 acts x 10 levels = 100 levels, generated by code but fully deterministic.
// Pure data + tiny helpers (no DOM, no storage, no three.js), so Node tests, the runner and the menus can all import it.
//
//   LEVELS[i] = {
//     id: 1..100, act: 1..10, idx: 1..10, name: 'İlk Kar', biome: 'snow', seed: uint32,
//     length: metres (500 at L1 -> 2600 at L100, with an in-act ramp), hardness: 0.7..1.8, startTier: 0..4,
//     features: ['waves', ...]            // every set-piece / mechanic allowed on this level (cumulative)
//     intro: { text, icon, feature } | null   // level that introduces something new -> show a tutorial card
//     goals: [ {star:1, kind:'finish', text},
//              {star:2, kind:'flakes', pct, text} | {star:2, kind:'flakesN', n, text},
//              {star:3, kind:'noloss'|'nocrash'|'maxsize'|'yeti'|'perfects'|'powerups', ...params, text} ],
//     boss: bool                          // idx 10: Yeti boss level (faster Yeti, throws boulders)
//   }
//
// Goal evaluation uses a stats object the runner fills at the end of a level (see evalGoals).

export const CAMPAIGN_SIZE = 100;
export const LEVELS_PER_ACT = 10;

// colors.a -> b -> c is the header gradient (sky -> horizon -> ground); accent is the node / path tint.
export const ACTS = [
  { id: 1, name: 'Karlı Zirve', biome: 'snow', icon: '❄️', colors: { a: '#3b8de6', b: '#86c6f4', c: '#dcefff' }, accent: '#7fc4ff' },
  { id: 2, name: 'Çam Ormanı', biome: 'forest', icon: '🌲', colors: { a: '#4a9be0', b: '#a2d3ee', c: '#7cc95a' }, accent: '#3f8a3a' },
  { id: 3, name: 'Yeşil Tepe', biome: 'greenhill', icon: '🌿', colors: { a: '#5bb8f0', b: '#a8e6a1', c: '#58c24c' }, accent: '#58c24c' },
  { id: 4, name: 'Kapadokya', biome: 'kapadokya', icon: '🎈', colors: { a: '#ff9f6b', b: '#f6d9b0', c: '#d98b5c' }, accent: '#e8895a' },
  { id: 5, name: 'Kasaba', biome: 'town', icon: '🏘️', colors: { a: '#4d9fee', b: '#98d2f6', c: '#e2a76a' }, accent: '#e0873f' },
  { id: 6, name: 'Çöl Kanyonu', biome: 'desert', icon: '🏜️', colors: { a: '#f2b24d', b: '#f7dd9a', c: '#d9964a' }, accent: '#e39a2d' },
  { id: 7, name: 'Buz Mağarası', biome: 'icecave', icon: '🧊', colors: { a: '#1d4a8a', b: '#58b8e8', c: '#bff0ff' }, accent: '#58d0ff' },
  { id: 8, name: 'Şeker Diyarı', biome: 'candy', icon: '🍭', colors: { a: '#ff8fc8', b: '#ffd0ea', c: '#c7a6ff' }, accent: '#ff6fb5' },
  { id: 9, name: 'Neon Gece', biome: 'neon', icon: '🌃', colors: { a: '#1a0f3d', b: '#5a1fa8', c: '#00b8d4' }, accent: '#00e5ff' },
  { id: 10, name: 'Volkan', biome: 'volcano', icon: '🌋', colors: { a: '#3a0f10', b: '#a3260f', c: '#ff8a1f' }, accent: '#ff7a1a' },
];

// Fun names: 9 normal levels + the boss (idx 10) for each act.
const NAMES = [
  ['İlk Kar', 'Tipi Başlıyor', 'Kızak Keyfi', 'Buz Sarkıtları', 'Kartopu Savaşı', 'Zirve Yolu', 'Soğuk Rüzgâr', 'Beyaz Sessizlik', 'Çığ Alarmı', "YETİ'NİN İNİ"],
  ['Çam Kokusu', 'Mantar Yolu', 'Kütük Köprüsü', 'Geyik Geçidi', 'Ormanda Kaybol', 'Reçine Kaçışı', 'Baykuş Gecesi', 'Dere Kenarı', 'Kestane Yağmuru', 'ORMANIN BEKÇİSİ'],
  ['Yeşil Yamaç', 'Papatya Tarlası', 'Koyun Sürüsü', 'Değirmen Yolu', 'Çimen Kaydırak', 'Arı Vızıltısı', 'Piknik Bozan', 'Gökkuşağı Tepesi', 'Çoban Ateşi', 'TEPENİN KRALI'],
  ['Peribacaları', 'Balon Festivali', 'Yeraltı Şehri', 'Güvercinlik', 'Testi Kebabı', 'Vadide Yankı', 'Balonlara Dikkat', 'Kaya Oteli', 'Gün Doğumu', 'PERİ BACASI YETİSİ'],
  ['Kasaba Meydanı', 'Pazar Yeri', 'Simitçi Kaçışı', 'Çay Bahçesi', 'Saat Kulesi', 'Trafik Telaşı', 'Çarşı İçi', 'Düğün Konvoyu', 'Bayram Yeri', 'ŞEHİR YETİSİ'],
  ['Kum Fırtınası', 'Vaha Rüyası', 'Develer Geçiyor', 'Serap', 'Kanyon Kaçışı', 'Kaktüs Slalomu', 'Sıcak Taşlar', 'Akrep Yolu', 'Çöl Gecesi', 'ÇÖLÜN EFENDİSİ'],
  ['Buz Kapısı', 'Kristal Koridor', 'Donmuş Şelale', 'Yankılı Mağara', 'Sarkıt Yağmuru', 'Aynalı Salon', 'Mavi Işık', 'Kaygan Tünel', 'Penguen Mahallesi', 'MAĞARANIN KALBİ'],
  ['Şeker Kapısı', 'Lokum Yolu', 'Çikolata Nehri', 'Marshmallow Tepesi', 'Bastonlu Slalom', 'Pamuk Bulutlar', 'Gofret Köprüsü', 'Dondurma Dağı', 'Karamel Kaçışı', 'TATLI YETİ'],
  ['Neon Girişi', 'Synthwave', 'Grid Koşusu', 'Hologram Sokağı', 'Lazer Labirenti', 'Disko Gecesi', 'Piksel Yağmuru', 'Gece Vardiyası', 'Elektrik Fırtınası', 'NEON YETİ'],
  ['Lav Kapısı', 'Kül Yağmuru', 'Kor Yolu', 'Gayzer Vadisi', 'Obsidyen Köprü', 'Magma Nehri', 'Kükürt Bulutu', 'Yanardağ Dibi', 'Son Tırmanış', 'BÜYÜK YETİ'],
];

// Level id at which each set-piece / mechanic first appears (it stays unlocked afterwards).
export const FEATURE_INTRO = {
  waves: 4, skiJump: 6, duck: 8, boulder: 10, chasm: 12, iceBridge: 14, oncoming: 17, halfpipe: 19, slideWall: 24,
  tube: 28, rail: 33, wind: 38, zipline: 44, fog: 51, loop: 58, corkscrew: 67,
};
const FEATURE_ORDER = Object.keys(FEATURE_INTRO).sort((a, b) => FEATURE_INTRO[a] - FEATURE_INTRO[b]);

// Tutorial cards. `feature` links a card to a FEATURE_INTRO entry; null = a basic control / system.
const INTROS = {
  1: { icon: '👆', text: 'Sağa ya da sola kaydır: şerit değiştir!', feature: null },
  2: { icon: '⬆️', text: 'Yukarı kaydır: zıpla!', feature: null },
  3: { icon: '⛄', text: 'Kar yığınlarını topla: büyürsün! Çarparsan küçülürsün.', feature: null },
  4: { icon: '🌊', text: 'Dalgalı pist! Tepelerde havalanabilirsin.', feature: 'waves' },
  5: { icon: '⬇️', text: 'Havadayken aşağı kaydır: yere çak!', feature: null },
  6: { icon: '🎿', text: 'Kayak rampası! Hızını al ve uç.', feature: 'skiJump' },
  7: { icon: '⚡', text: 'Güçlendirmeler: kask, mıknatıs, roket!', feature: null },
  8: { icon: '🙇', text: 'Aşağı kaydır: eğil! Alçak engellerin altından geç.', feature: 'duck' },
  10: { icon: '👹', text: "Yeti'nin İni! Yeti hızlı ve sana kaya fırlatıyor. Kayalardan kaç!", feature: 'boulder' },
  12: { icon: '🕳️', text: 'Uçurum! Zıpla ya da yana kaç.', feature: 'chasm' },
  14: { icon: '🧊', text: 'Buz köprü! Dar ve kaygan, dikkatli ol.', feature: 'iceBridge' },
  15: { icon: '🛷', text: 'Kızak: çift dokun, bir çarpışmayı affeder.', feature: null },
  17: { icon: '🚗', text: 'Karşıdan gelenler var! Şerit değiştir.', feature: 'oncoming' },
  19: { icon: '🛹', text: 'Yarım boru! Duvarlarda kay, havaya fırla.', feature: 'halfpipe' },
  24: { icon: '🧱', text: 'Kayan duvarlar! Boşluğu kolla.', feature: 'slideWall' },
  28: { icon: '🌀', text: 'Tünel! İçinde dönersin, dengeni koru.', feature: 'tube' },
  33: { icon: '🚃', text: 'Ray! Üstüne zıpla, kayarak ilerle.', feature: 'rail' },
  38: { icon: '💨', text: 'Rüzgâr seni yana iter. Direnme, kaydır!', feature: 'wind' },
  44: { icon: '🪢', text: 'Zip hattı! Tutun ve süzül.', feature: 'zipline' },
  51: { icon: '🌫️', text: 'Sis! Uzağı göremezsin, ritmi dinle.', feature: 'fog' },
  58: { icon: '🎢', text: 'Looping! Hızını koru, tepe taklak geç.', feature: 'loop' },
  67: { icon: '🔩', text: 'Burgu! Dönerek aşağı kay.', feature: 'corkscrew' },
};

const lerp = (a, b, t) => a + (b - a) * t;
const round5 = (x) => Math.round(x / 5) * 5;

function seedFor(id) {
  let h = Math.imul(id, 0x9e3779b1) ^ 0x85ebca6b;
  h = Math.imul(h ^ (h >>> 15), 0x2c1b3c6d);
  h = Math.imul(h ^ (h >>> 12), 0x297a2d39);
  return ((h ^ (h >>> 15)) >>> 0) || 1;
}

function star3Goal(id, idx, boss, act, length, startTier, t) {
  if (boss) {
    return act % 2 === 1
      ? { star: 3, kind: 'yeti', gap: 12, text: "Yeti 12 m'den fazla yaklaşmasın" }
      : { star: 3, kind: 'noloss', text: 'Hiç boyut kaybetme' };
  }
  const pool = ['noloss'];
  if (id >= 2) pool.push('nocrash');
  if (id >= 3) pool.push('yeti');
  if (id >= 5) pool.push('perfects');
  if (id >= 7) pool.push('powerups');
  if (length >= 1400 || startTier >= 2) pool.push('maxsize');
  const kind = id <= 3 ? 'noloss' : pool[(id * 3 + act) % pool.length];
  switch (kind) {
    case 'nocrash': return { star: 3, kind, text: 'Hiç çarpmadan bitir' };
    case 'maxsize': return { star: 3, kind, text: 'Maksimum boyutla bitir' };
    case 'yeti': return { star: 3, kind, gap: 10, text: "Yeti 10 m'den fazla yaklaşmasın" };
    case 'perfects': { const n = 3 + Math.round(t * 12); return { star: 3, kind, n, text: `${n} kez PERFECT yap` }; }
    case 'powerups': { const n = 2 + Math.round(t * 4); return { star: 3, kind, n, text: `${n} güçlendirme topla` }; }
    default: return { star: 3, kind: 'noloss', text: 'Hiç boyut kaybetme' };
  }
}

function build() {
  const out = [];
  for (let id = 1; id <= CAMPAIGN_SIZE; id++) {
    const act = Math.ceil(id / LEVELS_PER_ACT);
    const idx = ((id - 1) % LEVELS_PER_ACT) + 1;
    const boss = idx === LEVELS_PER_ACT;
    const t = (id - 1) / (CAMPAIGN_SIZE - 1);
    const u = (idx - 1) / (LEVELS_PER_ACT - 1);

    // in-act ramp: each act starts a little easier/shorter than it ends; endpoints land exactly on 500 and 2600
    const length = Math.round((lerp(532, 2500, t) * (0.94 + 0.1 * u)) / 10) * 10;
    const hardness = Math.round(Math.max(0.7, Math.min(1.8, lerp(0.7, 1.8, t) + 0.06 * (u - 0.5) + (boss ? 0.05 : 0))) * 100) / 100;
    const startTier = id <= 20 ? 1 : act >= 3 && idx === 7 ? 2 : 0;

    const features = FEATURE_ORDER.filter((f) => FEATURE_INTRO[f] <= id);
    const intro = INTROS[id] ? { ...INTROS[id] } : null;

    const pct = Math.max(40, Math.min(90, round5(40 + 45 * t + (idx % 3 === 0 ? 5 : 0))));
    const goal2 = idx % 4 === 0 && !boss
      ? (() => { const n = Math.max(10, round5((length / 8) * (pct / 100))); return { star: 2, kind: 'flakesN', n, text: `${n} kar tanesi topla` }; })()
      : { star: 2, kind: 'flakes', pct: pct / 100, text: `Kar tanelerinin %${pct}'ini topla` };

    out.push({
      id, act, idx, name: NAMES[act - 1][idx - 1], biome: ACTS[act - 1].biome, seed: seedFor(id),
      length, hardness, startTier, features, intro,
      goals: [{ star: 1, kind: 'finish', text: 'Bölümü bitir' }, goal2, star3Goal(id, idx, boss, act, length, startTier, t)],
      boss,
    });
  }
  return out;
}

export const LEVELS = build();

export const levelById = (id) => LEVELS[(Math.floor(Number(id)) || 0) - 1] || null;
export const actOf = (idOrLevel) => {
  const id = typeof idOrLevel === 'object' && idOrLevel ? idOrLevel.id : idOrLevel;
  return ACTS[Math.ceil((Number(id) || 1) / LEVELS_PER_ACT) - 1] || ACTS[0];
};
export const levelsOfAct = (act) => LEVELS.slice((act - 1) * LEVELS_PER_ACT, act * LEVELS_PER_ACT);

// stats the runner fills at the end of a campaign level (all optional except what the level's goals need):
//   { finished=true, flakes, flakesPct /*0..1 of the level's snowflakes*/, crashes, layersLost, maxTier, minYetiGap /*m*/, perfects, powerups, time }
// Returns [bool, bool, bool]. A level that was not finished earns nothing.
export function evalGoals(level, stats = {}) {
  const lv = typeof level === 'number' ? levelById(level) : level;
  if (!lv) return [false, false, false];
  const s = stats || {};
  const num = (x, d = 0) => (typeof x === 'number' && Number.isFinite(x) ? x : d);
  if (s.finished === false) return [false, false, false];
  return lv.goals.map((g) => {
    switch (g.kind) {
      case 'finish': return true;
      case 'flakes': return num(s.flakesPct) >= g.pct - 1e-9;
      case 'flakesN': return num(s.flakes) >= g.n;
      case 'noloss': return num(s.layersLost, 0) === 0;
      case 'nocrash': return num(s.crashes, 0) === 0;
      case 'maxsize': return num(s.maxTier) >= 4;
      case 'yeti': return num(s.minYetiGap, Infinity) >= g.gap;
      case 'perfects': return num(s.perfects) >= g.n;
      case 'powerups': return num(s.powerups) >= g.n;
      default: return false;
    }
  });
}
export const countStars = (met) => (Array.isArray(met) ? met.filter(Boolean).length : 0);
